### ISSUE TITLE
Fails to install with React 17+

### ISSUE THREAD

**Issue by iki** [awmleer/use-async-memo#9]
Error when `npm install use-async-memo`:
```
Could not resolve dependency:
peer react@"^16.8.0" from use-async-memo@1.2.2
```

On a `yarn` managed dependencies it can be fixed with [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)
```
  "resolutions": {
    "react": "17.0.1"
  }
```
with `npm` we have to wait for [overrides](https://github.com/npm/statusboard/issues/343), and the [existing workarounds](https://stackoverflow.com/a/65014694/368691) are not nice

**Comment by awmleer** [comment]
This is due to the outdated peer dependencies config in `package.json`. I'll update it asap.

https://github.com/awmleer/use-async-memo/blob/9d6b7a792823b2ae46581e879c226d8851805e62/package.json#L35

**Comment by awmleer** [comment]
Fixed via 98268b4.

**Comment by awmleer** [comment]
@iki Please reinstall this package or upgrade it to v1.2.3. It should be working now. Thanks for opening this issue.

**Comment by iki** [comment]
@awmleer thanks for a super fast fix, works now 💯
